# Generated by Django 3.1.6 on 2021-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=750)),
                ('content', models.TextField()),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('contact_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
